# This is a basic workflow to help you get started with Actions

name: healthcheck

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Docker Image Version
        id: set_version
        run: echo "::set-output name=VERSION::$(git rev-parse --short HEAD)"

      - name: Build and tag image
        id: build-image
        env:
          ECR_REGISTRY: 058264180972.dkr.ecr.eu-west-2.amazonaws.com
          ECR_REPOSITORY: healthcheck_prod
          IMAGE_TAG: ${{ steps.set_version.outputs.VERSION }}
        run: |
          docker build -t 058264180972.dkr.ecr.eu-west-2.amazonaws.com/healthcheck_prod:$IMAGE_TAG .
          docker push 058264180972.dkr.ecr.eu-west-2.amazonaws.com/healthcheck_prod:$IMAGE_TAG
